### ISSUE TITLE
Operations End Unexpectedly

### ISSUE THREAD

**Issue by shervasElec** [NaN-tic/trytond-production_operation_tracking#6]
To reproduce, we have 2 productions:

FAB01: state='assigned', 1 operation in a state != 'planned', work_center=27, work_center.type = 'employee'

FAB02: 1 operation in running state, work_center=27.

Then, the FAB01 is run.
In that moment, the line of the operation of FAB02 that was running, is ended and the state of the operation remains in 'running' when it's actually done.
Also it happens when he operation of the FAB01 is passed to done.

I don't find the point of this functioning.
The method where the operation line is ended, is executed when an operation is passed to wait (or his production run), or when an operation is done.
https://github.com/NaN-tic/trytond-production_operation_tracking/blob/5d2758260c56ccd6692a44c24f993d213da0fe2f/operation.py#L63

**Comment by raimonesteve** [comment]
See #7
